INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M416', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('AKM', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('SCAR-L', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M16A4', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('UMP9', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('S1897', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('S686', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('S12K', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Micro UZI', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Tommy Gun', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Kar98k', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M416', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M16A4', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('SCAR-L', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Mini 14', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('SKS', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('AKM', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('UMP9', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M24', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('AWM', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M416', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('AKM', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('SCAR-L', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M16A4', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('UMP9', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('S1897', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('S686', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('S12K', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Micro UZI', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Tommy Gun', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Kar98k', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M416', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M16A4', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('SCAR-L', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('Mini 14', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('SKS', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('AKM', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('UMP9', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('M24', 0);
INSERT INTO pubg.zk_distance_armgs (armgs, per) VALUES ('AWM', 0);